# Generated by Django 5.2 on 2025-05-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('part_of_speech', models.CharField(blank=True, max_length=10)),
                ('definition', models.TextField()),
                ('sentence', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
