# Generated by Django 5.2 on 2025-08-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_practicesession_wordattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordattempt",
            name="session",
        ),
        migrations.RemoveField(
            model_name="wordattempt",
            name="word",
        ),
        migrations.DeleteModel(
            name="PracticeSession",
        ),
        migrations.DeleteModel(
            name="WordAttempt",
        ),
    ]
